wallpaper {
    monitor = DP-1
    path = /workspace/file storage/Wallpaper/EAGLE_WALLPAPER.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /workspace/file storage/Wallpaper/EAGLE_WALLPAPER.png
    fit_mode = cover
}
